/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Car;
import model.CarHistory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shwetawakale
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    CarHistory history;
    
    public SearchJPanel(CarHistory history){
        initComponents();
        
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSYear = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSManuf = new javax.swing.JLabel();
        lblSCity = new javax.swing.JLabel();
        lblSSerial = new javax.swing.JLabel();
        lblSModel = new javax.swing.JLabel();
        lblSSeat = new javax.swing.JLabel();
        txtSYear = new javax.swing.JTextField();
        txtSManuf = new javax.swing.JTextField();
        txtSCity = new javax.swing.JTextField();
        txtSSerial = new javax.swing.JTextField();
        txtSModel = new javax.swing.JTextField();
        txtSSeat = new javax.swing.JTextField();
        btnSYear = new javax.swing.JButton();
        btnSManuf = new javax.swing.JButton();
        btnSCity = new javax.swing.JButton();
        btnSModel = new javax.swing.JButton();
        btnSSerial1 = new javax.swing.JButton();
        btnSSeat = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();

        lblSYear.setText("Year");

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SEARCH");

        lblSManuf.setText("Manufacturer");

        lblSCity.setText("City");

        lblSSerial.setText("Serial Number");

        lblSModel.setText("Model Number");

        lblSSeat.setText("Seat");

        txtSYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSYearActionPerformed(evt);
            }
        });

        txtSModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSModelActionPerformed(evt);
            }
        });

        txtSSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSeatActionPerformed(evt);
            }
        });

        btnSYear.setText("Search");
        btnSYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSYearActionPerformed(evt);
            }
        });

        btnSManuf.setText("Search");
        btnSManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSManufActionPerformed(evt);
            }
        });

        btnSCity.setText("Search");
        btnSCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCityActionPerformed(evt);
            }
        });

        btnSModel.setText("Search");
        btnSModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSModelActionPerformed(evt);
            }
        });

        btnSSerial1.setText("Search");
        btnSSerial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSSerial1ActionPerformed(evt);
            }
        });

        btnSSeat.setText("Search");
        btnSSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSSeatActionPerformed(evt);
            }
        });

        btnFirst.setText("First Available Passanger Cars");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Available", "Year of Manuf", "Seat No", "Serial No", "Model No", "Avail in City", "Certificate", "Used by Uber", "Fleet Catalog"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCars);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSYear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSManuf)
                    .addComponent(lblSCity))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtSYear, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSYear))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSCity, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSCity))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSManuf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSManuf)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSSerial)
                    .addComponent(lblSModel)
                    .addComponent(lblSSeat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSSeat))
                    .addComponent(txtSSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSModel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSModel)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnFirst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(699, Short.MAX_VALUE)
                    .addComponent(btnSSerial1)
                    .addGap(16, 16, 16)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSModel, btnSSeat, btnSSerial1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSCity, btnSManuf, btnSYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSYear)
                    .addComponent(lblSSerial)
                    .addComponent(txtSYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSManuf)
                    .addComponent(lblSModel)
                    .addComponent(txtSManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSManuf)
                    .addComponent(btnSModel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCity)
                    .addComponent(lblSSeat)
                    .addComponent(txtSCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSCity)
                    .addComponent(btnSSeat))
                .addGap(31, 31, 31)
                .addComponent(btnFirst)
                .addContainerGap(532, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(btnSSerial1)
                    .addContainerGap(650, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
           if(c.getAvail().equals("Available")){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
               
              
            
            
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnSSerial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSSerial1ActionPerformed
        // TODO add your handling code here:
        String matchSerialNum= txtSSerial.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            
            String sn=c.getSerialnum();
           if(sn.equals(matchSerialNum)){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        }      
              
    }//GEN-LAST:event_btnSSerial1ActionPerformed

    private void txtSYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSYearActionPerformed

    private void btnSYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSYearActionPerformed
        // TODO add your handling code here:
        String matchYear= txtSYear.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            
            String y=String.valueOf(c.getYearofM());
            
           if(y.equals(matchYear)){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        }  
        
    }//GEN-LAST:event_btnSYearActionPerformed

    private void btnSManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSManufActionPerformed
        // TODO add your handling code here:
        String matchManuf= txtSManuf.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            
            String m=c.getManuf();
           if(m.equals(matchManuf)){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        }     
    }//GEN-LAST:event_btnSManufActionPerformed

    private void btnSCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCityActionPerformed
        // TODO add your handling code here:
        
        String matchCity= txtSCity.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            
            String city=c.getCity();
           if(city.equals(matchCity)){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        }     
    }//GEN-LAST:event_btnSCityActionPerformed

    private void btnSModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSModelActionPerformed
        // TODO add your handling code here:
        String matchModel= txtSModel.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            
            String mo=c.getModelnum();
           if(mo.equals(matchModel)){
              
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        }     
    }//GEN-LAST:event_btnSModelActionPerformed

    private void txtSSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSeatActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_txtSSeatActionPerformed

    private void txtSModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSModelActionPerformed

    private void btnSSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSSeatActionPerformed
        // TODO add your handling code here:
        String matchSeat= txtSSeat.getText();
        
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        
        for(Car c: history.getHistory()){
            System.out.println("Check.... ");
            
            String s=c.getSeatnum();
           if(s.equalsIgnoreCase(matchSeat)){
//              System.out.println("Check.... ");
               Object[] row= new Object[8];
            
            //row[0]=c;
            row[0]=c;
            row[1]=c.getAvail();
            row[2]=c.getYearofM();
//            txtSYear.setText(Long.toString(c.getYearofM()));
            row[3]=c.getSeatnum();
            row[4]=c.getSerialnum();
            row[5]=c.getModelnum();
            row[6]=c.getCity();
            row[7]=c.getFleet();
            
            
            model.addRow(row);
           }
        } 
    }//GEN-LAST:event_btnSSeatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnSCity;
    private javax.swing.JButton btnSManuf;
    private javax.swing.JButton btnSModel;
    private javax.swing.JButton btnSSeat;
    private javax.swing.JButton btnSSerial1;
    private javax.swing.JButton btnSYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSCity;
    private javax.swing.JLabel lblSManuf;
    private javax.swing.JLabel lblSModel;
    private javax.swing.JLabel lblSSeat;
    private javax.swing.JLabel lblSSerial;
    private javax.swing.JLabel lblSYear;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtSCity;
    private javax.swing.JTextField txtSManuf;
    private javax.swing.JTextField txtSModel;
    private javax.swing.JTextField txtSSeat;
    private javax.swing.JTextField txtSSerial;
    private javax.swing.JTextField txtSYear;
    // End of variables declaration//GEN-END:variables
}
